In [1]:
# 关闭warnings
import warnings
warnings.filterwarnings('ignore')

import tensorflow as tf 
import numpy as np

TF的编程模型

In [2]:
# 计算两个数的乘积
se = tf.Session()
x = tf.placeholder(tf.float32,[1], name="x")
y = tf.placeholder(tf.float32,[1], name="y")

b = tf.constant(2.0)
y = x * b 
x_in = [100]
y_output = se.run(y, {x:x_in})
print(y_output)

se.close()

[200.]


TF的数据模型用`张量`表示。张量有三个属性：阶、形状和数据类型。

每个张量的维度单位用阶来描述。它定义了张量的维数，因此，也被称为一个张量的量级或张量的n个维。零阶张量是一个标量，一阶张量是一个向量，二阶张量是一个矩阵。

In [3]:
scalar = tf.constant(100) 
scalar.get_shape()

TensorShape([])

In [4]:
vector = tf.constant([1,2,3,4,5]) 
vector.get_shape()

TensorShape([Dimension(5)])

In [5]:
matrix = tf.constant([[1,2,3],[4,5,6]]) 
matrix.get_shape()

TensorShape([Dimension(2), Dimension(3)])

In [6]:
cube_matrix = tf.constant([[[1],[2],[3]],[[4],[5],[6]],[[7],[8],[9]]])
cube_matrix.get_shape()

TensorShape([Dimension(3), Dimension(3), Dimension(1)])

TensorFlow中数据的传递需要通过其API与NumPy数组的交互来完成。

若要使用常数构建张量，需要将一个NumPy数组传入`tf.constant()`操作符，得到一个拥有该值的TensorFlow张量：

In [7]:
numpy_1d = np.array([1,2,3,4,5,6,7,8,9,10]) 
tensor_1d = tf.constant(numpy_1d) 

with tf.Session() as sess:
    print(tensor_1d.get_shape()) 
    print(sess.run(tensor_1d))

(10,)
[ 1  2  3  4  5  6  7  8  9 10]


若要使用变量构建张量，将变量定义为NumPy数组的形式，并将其传入`tf.Variable`函数，变量是由`tf.Variable()`语句创建的。

In [8]:
numpy_2d = np.array([(1,2,3),(4,5,6),(7,8,9)]) 
tensor_2d = tf.Variable(numpy_2d) 

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer()) 
    print(tensor_2d.get_shape()) 
    print(sess.run(tensor_2d))

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


TensorFlow中另一种定义张量的方式是，使用`tf.conbert_to_tensor`命令：

In [9]:
numpy_3d = np.array([[[ 0, 1, 2],[ 3, 4, 5],[ 6, 7, 8]],[[ 9, 10, 11],[12, 13, 14],[15, 16, 17]], [[18, 19, 20],[21, 22, 23],[24, 25, 26]]])
tensor_3d = tf.convert_to_tensor(numpy_3d, dtype=tf.float64) 

with tf.Session() as sess:
    print(tensor_3d.get_shape()) 
    print(sess.run(tensor_3d))

(3, 3, 3)
[[[ 0.  1.  2.]
  [ 3.  4.  5.]
  [ 6.  7.  8.]]

 [[ 9. 10. 11.]
  [12. 13. 14.]
  [15. 16. 17.]]

 [[18. 19. 20.]
  [21. 22. 23.]
  [24. 25. 26.]]]


为取回操作的输出，需要调用Session对象中的run()函数，并传入需要取回的张量。除了可以取回单一的张量节点外，你还可以取回多个张量：

In [10]:
constant_A = tf.constant([100.0]) 
constant_B = tf.constant([300.0]) 
constant_C = tf.constant([3.0])

sum_ = tf.add(constant_A, constant_B) 
mul_ = tf.multiply(constant_A, constant_C)

with tf.Session() as sess:
    result = sess.run([sum_,mul_]) 
    print(result)

[array([400.], dtype=float32), array([300.], dtype=float32)]


注入机制将张量插入图节点，它用一个张量值暂时替代操作的输出。注入机制只用于在调用run函数时，通过feed_dict传递参数：

In [11]:
a = 3 
b = 2 

x = tf.placeholder(tf.float32, shape=(a, b)) 
y = tf.add(x, x) 

data = np.random.rand(a, b) 

sess = tf.Session() 
print(sess.run(y, feed_dict={x:data}))

[[1.3474222  0.9640931 ]
 [1.5801455  1.0430323 ]
 [1.2523843  0.77103126]]
